server:
  port: 8000
  servlet:
    context-path: /admin

spring:
  security:
    user:
      name: apn
      password: apn

  boot:
    admin:
      ui:
        title: APN Admin Monitor

application:
  notification:
    lark:
      enabled: true
      webhookKey: gRN7zwUVVeddC6bUVL4cYd
      webhookUrl: https://open.larksuite.com/open-apis/bot/v2/hook/3789e9f0-2a59-4e92-9a0a-a2b7849cb177