mode: command

from:
  addr: 127.0.0.1:8848
  namespace: z-dev-zzc
  username: nacos
  password: nacos
to:
  addr: 127.0.0.1:8848
  namespace: test-sync
  username: nacos
  password: nacos

ignore:
  - data_id: public-datasource.yaml
    fields:
      spring:
        liquibase:
          enabled:

